import pandas as pd
# ^^^ pyforest auto-imports - don't write above this line
# Data Manipulation

## Learnings:

- rename columns in a DataFrame
- manipulate columns in a DataFrame (select, reorder, delete)
- filter dataframe
- assign to a column based on a condition

In [1]:
import pandas as pd

data = pd.read_csv('data/vehicles.csv')
data.head(2)

FileNotFoundError: [Errno 2] No such file or directory: 'data/vehicles.csv'

In [ ]:
data.shape

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB

## Checking the dataframe column names

Rename all columns at once:
- `data.columns` is an **attribute** of the DataFrame which results in a list-like of the column names
    - You can substitute it by another list containing the names you want 
    - Note you have to substitute the whole set of column names at once
    
- `data.rename()` is a **method** of a DataFrame, in which you can rename one column at once
    - You just need to pass a dictionary containing {'old_name':'new_name'} 
    - By default, it changes names of a **index** (`axis=0`), you can specify `axis=1` to change **column** names
    - the `inplace` argument

In [6]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

### Substituting `.columns` attribute

In [ ]:
# say for example we want to convert all columns to lowercase!

In [7]:
data.columns = ['make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
               'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
               'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
               'CO2 Emission Grams/Mile', 'xxxxxxx']

In [8]:
data.head()

,make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,xxxxxxx
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [9]:
data.columns = ['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
               'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
               'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
               'CO2 Emission Grams/Mile', 'Fuel Cost/Year']

In [13]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

In [20]:
colnames = []
for col in data.columns:
    colnames.append(col.lower())

In [27]:
data.columns = [col.lower().replace(' ','_').replace('/','_') for col in data.columns]

In [28]:
data.head()

,make,model,year,engine_displacement,cylinders,transmission,drivetrain,vehicle_class,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [30]:
data.columns = ['manufacturer']

ValueError: Length mismatch: Expected axis has 15 elements, new values have 1 elements

### `.rename() method`

`.rename({'old_column':'new_column'})`

#### returning a new dataframe

In [33]:
data.rename({'make': 'manufacturer'}, axis=1)

,manufacturer,model,year,engine_displacement,cylinders,transmission,drivetrain,vehicle_class,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [35]:
data.rename(columns={'make': 'manufacturer', 'year':'model_year'})

,manufacturer,model,model_year,engine_displacement,cylinders,transmission,drivetrain,vehicle_class,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [ ]:
data = data.rename(columns={'make': 'manufacturer', 'year':'model_year'})

In [36]:
data.head()

,make,model,year,engine_displacement,cylinders,transmission,drivetrain,vehicle_class,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

#### inplace

In [37]:
data.rename({'engine_displacement': 'engine_displacement2',
             'vehicle_class': 'vehicle_class2'}, axis=1, inplace=True)

In [38]:
# dataframe already changed
data.head()

,make,model,year,engine_displacement2,cylinders,transmission,drivetrain,vehicle_class2,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

If you try to assign an `inplace=True` command, check what happens:

In [55]:
data.rename({'year3': 'year10'}, axis=1)

,make,model,year10,engine_displacement2,cylinders,transmission,drivetrain,vehicle_class2,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [45]:
y = data.rename({'year': 'year3'}, axis=1, inplace=True)

In [46]:
data.head()

,make,model,year3,engine_displacement2,cylinders,transmission,drivetrain,vehicle_class2,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [52]:
print(y)

None

Two options:
> 1. store it again on the variable `data`: 

    data = data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'})
> 2. Use the inplace argument `inplace =  True` to change the values within the dataframe automatically

    data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'}, inplace=True)

In [58]:
# You can also assign to a different variable, of course
renamed_data = data.rename(columns={'make':'Manufacturer', 'year3':'ANO'})

In [59]:
renamed_data.head(2)

,Manufacturer,model,ANO,engine_displacement2,cylinders,transmission,drivetrain,vehicle_class2,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550

In [60]:
data.head(2)

,make,model,year3,engine_displacement2,cylinders,transmission,drivetrain,vehicle_class2,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile,fuel_cost_year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550

## Reordering columns in a dataframe

>    - Remember you always pass a list of columns to access a dataframe

Just select the columns in a different order and overwrite the previous dataframe

In [64]:
data[['make','model']]

                   make                model
0            AM General    DJ Po Vehicle 2WD
1            AM General     FJ8c Post Office
2            AM General  Post Office DJ5 2WD
3            AM General  Post Office DJ8 2WD
4      ASC Incorporated                  GNX
...                 ...                  ...
35947             smart         fortwo coupe
35948             smart         fortwo coupe
35949             smart         fortwo coupe
35950             smart         fortwo coupe
35951             smart         fortwo coupe

[35952 rows x 2 columns]

In [65]:
data[['model', 'make']]

                     model              make
0        DJ Po Vehicle 2WD        AM General
1         FJ8c Post Office        AM General
2      Post Office DJ5 2WD        AM General
3      Post Office DJ8 2WD        AM General
4                      GNX  ASC Incorporated
...                    ...               ...
35947         fortwo coupe             smart
35948         fortwo coupe             smart
35949         fortwo coupe             smart
35950         fortwo coupe             smart
35951         fortwo coupe             smart

[35952 rows x 2 columns]

In [66]:
data.columns

Index(['make', 'model', 'year3', 'engine_displacement2', 'cylinders',
       'transmission', 'drivetrain', 'vehicle_class2', 'fuel_type',
       'fuel_barrels_year', 'city_mpg', 'highway_mpg', 'combined_mpg',
       'co2_emission_grams_mile', 'fuel_cost_year'],
      dtype='object')

In [68]:
data = data[['fuel_cost_year', 'make', 'model', 'year3', 'engine_displacement2', 'cylinders',
       'transmission', 'drivetrain', 'vehicle_class2', 'fuel_type',
       'fuel_barrels_year', 'city_mpg', 'highway_mpg', 'combined_mpg',
       'co2_emission_grams_mile']]

In [69]:
data

,fuel_cost_year,make,model,year3,engine_displacement2,cylinders,transmission,drivetrain,vehicle_class2,fuel_type,fuel_barrels_year,city_mpg,highway_mpg,combined_mpg,co2_emission_grams_mile
0,1950,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706
1,2550,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385
2,2100,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500
3,2550,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385
4,2550,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,1100,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000
35948,1100,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000
35949,1100,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000
35950,1100,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000
35951,1150,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000

In [73]:
data.loc[:, 'model','make'] # WRONG - not a list, you passed a string, string - not a list.

IndexingError: Too many indexers

How can I get the `fuel cost/year` variable and put it at the beginning of the dataframe

In [74]:
data.columns

Index(['fuel_cost_year', 'make', 'model', 'year3', 'engine_displacement2',
       'cylinders', 'transmission', 'drivetrain', 'vehicle_class2',
       'fuel_type', 'fuel_barrels_year', 'city_mpg', 'highway_mpg',
       'combined_mpg', 'co2_emission_grams_mile'],
      dtype='object')

In [75]:
column_order = ['co2_emission_grams_mile', 'fuel_cost_year', 'make', 'model', 'year3', 'engine_displacement2',
       'cylinders', 'transmission', 'drivetrain', 'vehicle_class2',
       'fuel_type', 'fuel_barrels_year', 'city_mpg', 'highway_mpg',
       'combined_mpg', ]

data = data.loc[:, column_order]

In [76]:
# problems you may handle

# auto-assign a subset of the dataframe
data = data['make']

In [77]:
data.head(2)

0    AM General
1    AM General
Name: make, dtype: object

In [78]:
data = pd.read_csv('data/vehicles.csv')

In [79]:
# assign an inplace=True command:
data = data.rename({'Year':'Model_Year'}, axis=1, inplace=True)

In [80]:
data.head(2)

AttributeError: 'NoneType' object has no attribute 'head'

In [81]:
print(data)

None

## Remove column

- The `.drop()` method

In [82]:
data = pd.read_csv('data/vehicles.csv')

In [84]:
data.drop('Year')

KeyError: "['Year'] not found in axis"

In [ ]:
data.drop('Year')

In [85]:
data.drop('Year', axis=1)

,Make,Model,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [94]:
data.drop(1)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
5,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [91]:
data.drop(1).reset_index().drop('index', axis=1)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
2,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
3,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
4,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35946,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35947,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35948,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35949,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [96]:
data.drop(1).reset_index(drop=True)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
2,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
3,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
4,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35946,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35947,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35948,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35949,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

# Filter records
>    - `mask` concept
>    - `.query()` method

This is really important for data wrangling.

In [1]:
data = pd.read_csv('data/vehicles.csv')

In [2]:
data.head(2)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550

## Simple Example: Starting with a numpy array. How can I filter the values of a list?

In [27]:
import numpy as np

In [28]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [33]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
my_array * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [34]:
my_array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

The results of `my_array > 5` is what is called **a mask**. A result containing the `True` and `False` results of an operation.

In [8]:
my_array[5:]

array([ 6,  7,  8,  9, 10])

In [35]:
my_array[ [False, False, False, False, False,  True,  True,  True,  True, True] ]

array([ 6,  7,  8,  9, 10])

In [36]:
my_array[my_array < 8]

array([1, 2, 3, 4, 5, 6, 7])

Masks can be used as an index to select data!

In [11]:
my_array[ [False, False, False, False, False,  True,  True,  True,  True, True] ]

array([ 6,  7,  8,  9, 10])

In [37]:
my_array[ my_array > 5 ]

array([ 6,  7,  8,  9, 10])

After selecting, you can do anything with it, for example assigning it. This operation is called a `vectorial` operation. It is done all at once.

In [38]:
my_array[my_array > 5] = 1000

In [39]:
my_array

array([   1,    2,    3,    4,    5, 1000, 1000, 1000, 1000, 1000])

In [40]:
my_matrix = np.random.randint(0, 10, size=(5,5))
my_matrix

array([[2, 2, 5, 8, 0],
       [6, 3, 9, 6, 6],
       [4, 7, 9, 6, 4],
       [5, 0, 7, 9, 4],
       [6, 1, 0, 4, 9]])

In [41]:
my_matrix > 5

array([[False, False, False,  True, False],
       [ True, False,  True,  True,  True],
       [False,  True,  True,  True, False],
       [False, False,  True,  True, False],
       [ True, False, False, False,  True]])

In [42]:
my_matrix[ my_matrix > 5 ] = -99999

In [43]:
my_matrix

array([[     2,      2,      5, -99999,      0],
       [-99999,      3, -99999, -99999, -99999],
       [     4, -99999, -99999, -99999,      4],
       [     5,      0, -99999, -99999,      4],
       [-99999,      1,      0,      4, -99999]])

In [20]:
my_array[ my_array > 5 ] = 10

In [21]:
my_array

array([ 1,  2,  3,  4,  5, 10, 10, 10, 10, 10])

You can also save the condition

In [45]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [46]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
condition = my_array > 5 
condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
my_array[ condition ]

array([ 6,  7,  8,  9, 10])

## Bitwise logical operators - Combining conditions

To make more than one condition together, you can use 
- `&` - analogous to `and`
- `|` - analogous to `or`

For example, get all numbers from my_array that are greater than 3 and smaller than 8

Let's do it in steps:
- get values greater than 3

In [52]:
my_array[my_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

- get values smaller than 8

In [53]:
my_array[my_array < 8]

array([1, 2, 3, 4, 5, 6, 7])

- get values greater than 3 and smaller than 8

In [73]:
greater_than_3 = my_array > 3

In [74]:
smaller_than_8 = my_array < 8

In [68]:
(my_array > 3) & (my_array < 8)

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [67]:
# (my_array > 3) or (my_array < 8)
(my_array > 3) | (my_array < 8)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [69]:
(my_array > 3) & (my_array < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [75]:
greater_than_3 & smaller_than_8

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

## Now in a dataframe

Let's find the rows in which the Cylinders values are exactly 6.

In [76]:
data

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [79]:
data['Cylinders'] == 4

0         True
1        False
2         True
3        False
4        False
         ...
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Cylinders, Length: 35952, dtype: bool

In [1]:
data['Cylinders'] == 4

NameError: name 'data' is not defined

In [ ]:
data.loc[:, 'Cylinders']

In [82]:
data.loc[data['Cylinders'] == 4, :]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
5,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500
6,Acura,2.2CL/3.0CL,1997,2.2,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,22,28,24,370.291667,1400
8,Acura,2.3CL/3.0CL,1998,2.3,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,19,27,22,403.954545,1500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35927,Yugo,GV Plus/GV/Cabrio,1990,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350
35928,Yugo,GV/GVX,1987,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300
35929,Yugo,GV/GVX,1989,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300
35930,Yugo,GV/GVX,1989,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350
35931,Yugo,Gy/yugo GVX,1986,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Minicompact Cars,Regular,13.184400,22,29,25,355.480000,1350

### Example

In [85]:
# create a column with all zeroes named - 'fl_city_car'

data['fl_city_car'] = 0

In [89]:
(data['City MPG']) > (data['Highway MPG'])

0         True
1        False
2        False
3        False
4        False
         ...
35947    False
35948    False
35949    False
35950    False
35951    False
Length: 35952, dtype: bool

In [92]:
# assign 1 to 'fl_city_car' all cars that have 'City MPG' > 'Highway MPG'

data.loc[(data['City MPG']) > (data['Highway MPG']), 'fl_city_car'] = 1

In [96]:
data.loc[(data['City MPG']) > (data['Highway MPG']), 'fl_city_car'] = 10

In [98]:
data.loc[(data['City MPG']) > (data['Highway MPG']), 'fl_city_car']

0        10
47       10
48       10
3069     10
3070     10
         ..
33293    10
33294    10
33295    10
33374    10
33375    10
Name: fl_city_car, Length: 183, dtype: int64

## You can combine conditions

Cars from `Ford` and 6 `Cylinders`

In [99]:
data.loc[:, :]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,10
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,0
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,0
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,0
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,0
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,0
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,0
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,0
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,0

In [108]:
data['std'] = data[['City MPG','Highway MPG','Combined MPG']].std(axis=1)

In [110]:
data.loc[data['std'] != 0, :]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car,std
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,10,0.577350
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,0,0.577350
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,0,3.605551
5,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500,0,3.055050
6,Acura,2.2CL/3.0CL,1997,2.2,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,22,28,24,370.291667,1400,0,3.055050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,0,2.000000
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,0,2.000000
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,0,2.000000
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,0,2.516611
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,0,3.511885

In [104]:
data.loc[(data['Cylinders'] == 6) & (data['Make'] == 'Ford'), :]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car
11442,Ford,Aerostar Van,1986,2.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,21,17,522.764706,1950,0
11443,Ford,Aerostar Van,1986,2.8,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,18.311667,16,22,18,493.722222,1850,0
11444,Ford,Aerostar Van,1986,3.0,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,17.347895,17,22,19,467.736842,1750,0
11445,Ford,Aerostar Van,1986,3.0,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,18.311667,15,22,18,493.722222,1850,0
11448,Ford,Aerostar Van,1987,3.0,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,17.347895,16,22,19,467.736842,1750,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14381,Ford,Windstar FWD Wagon,2000,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950,0
14382,Ford,Windstar FWD Wagon,2000,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950,0
14383,Ford,Windstar FWD Wagon,2001,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,22,18,493.722222,1850,0
14384,Ford,Windstar FWD Wagon,2002,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,21,18,493.722222,1850,0
14385,Ford,Windstar FWD Wagon,2003,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,22,18,493.722222,1850,0

In [105]:
# careful with:

data.loc[data['Make']=='Ford' & data['Cylinders']==6, :] # WRONG!!

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

## You can put the conditions in variables as well

In [111]:
condition1 = (data['Make']=='Ford')
condition2 = (data['Cylinders']==6)
condition3 = (data['Combined MPG'] < 18)

In [112]:
data.loc[condition1 & condition2 & condition3, :]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car,std
11442,Ford,Aerostar Van,1986,2.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
11450,Ford,Aerostar Van,1988,3.0,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,20,17,522.764706,1950,0,2.516611
11452,Ford,Aerostar Van,1989,3.0,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
11456,Ford,Aerostar Van,1990,4.0,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,20,17,522.764706,1950,0,2.516611
11459,Ford,Aerostar Van,1991,4.0,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,20,17,522.764706,1950,0,2.516611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14376,Ford,Windstar FWD Wagon,1997,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
14379,Ford,Windstar FWD Wagon,1999,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
14380,Ford,Windstar FWD Wagon,1999,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
14381,Ford,Windstar FWD Wagon,2000,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
14382,Ford,Windstar FWD Wagon,2000,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050

## Another way to do the same thing.

* using the method `query`

The method `query` receives a string in which you can say your condition. Important things:
- `.query()` is a method of your dataframe
- `.query()` method receives a string 
- Every word inside the string that is not `quoted` is considered a variable of your dataframe (so, for example `.query('Year == 1999')` will look for the variable `Year`. Another example: if you try to run `.query('Make == Ford')` will look both for the column name `Make` and the column named `Ford`. If you want the results of the column `Make` to match the **string** Ford, you have to run `.query('Make == "Ford"')`
- If your column has spaces, you have to call it using backticks like in **.query('\`Engine Displacement\` < 4')**:

In [123]:
indexes = list(data.index)
indexes.insert(0, 'Make')

In [125]:
indexes.remove(0)

In [126]:
data.index = indexes

In [130]:
data.query('Make == "Ford"')

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car,std
11440,Ford,Aerostar Van,1986,2.3,4.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,17.347895,18,22,19,467.736842,1750,0,2.081666
11441,Ford,Aerostar Van,1986,2.3,4.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,13.733750,23,26,24,370.291667,1400,0,1.527525
11442,Ford,Aerostar Van,1986,2.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
11443,Ford,Aerostar Van,1986,2.8,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,18.311667,16,22,18,493.722222,1850,0,3.055050
11444,Ford,Aerostar Van,1986,3.0,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,17.347895,17,22,19,467.736842,1750,0,2.516611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14381,Ford,Windstar FWD Wagon,2000,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
14382,Ford,Windstar FWD Wagon,2000,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950,0,3.055050
14383,Ford,Windstar FWD Wagon,2001,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,22,18,493.722222,1850,0,3.055050
14384,Ford,Windstar FWD Wagon,2002,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,21,18,493.722222,1850,0,2.516611
14385,Ford,Windstar FWD Wagon,2003,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,22,18,493.722222,1850,0,3.055050

In [114]:
data.query('Cylinders == 4 and Make == "Ford"')

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car,std
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,10,0.577350
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,0,0.577350
5,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500,0,3.055050
6,Acura,2.2CL/3.0CL,1997,2.2,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,22,28,24,370.291667,1400,0,3.055050
8,Acura,2.3CL/3.0CL,1998,2.3,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,19,27,22,403.954545,1500,0,4.041452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35927,Yugo,GV Plus/GV/Cabrio,1990,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350,0,2.516611
35928,Yugo,GV/GVX,1987,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300,0,2.516611
35929,Yugo,GV/GVX,1989,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300,0,2.516611
35930,Yugo,GV/GVX,1989,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350,0,2.516611
35931,Yugo,Gy/yugo GVX,1986,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Minicompact Cars,Regular,13.184400,22,29,25,355.480000,1350,0,3.511885

In [115]:
data.query('`City MPG` > `Highway MPG`')

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car,std
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,10,0.577350
47,Acura,ILX Hybrid,2013,1.5,4.0,Auto(AV-S7),Front-Wheel Drive,Compact Cars,Premium,8.673947,39,38,38,228.000000,1050,10,0.577350
48,Acura,ILX Hybrid,2014,1.5,4.0,Auto(AV-S7),Front-Wheel Drive,Compact Cars,Premium,8.673947,39,38,38,228.000000,1050,10,0.577350
3069,BMW,i3 REX,2014,0.6,2.0,Auto(A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,40.000000,1050,10,2.000000
3070,BMW,i3 REX,2015,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,40.000000,1050,10,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33293,Toyota,Prius v,2015,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Station Wagons,Regular,7.847857,44,40,42,211.000000,800,10,2.000000
33294,Toyota,Prius v,2016,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Station Wagons,Regular,7.847857,44,40,42,211.000000,800,10,2.000000
33295,Toyota,Prius v,2017,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Station Wagons,Regular,8.039268,43,39,41,217.000000,800,10,2.000000
33374,Toyota,RAV4 Hybrid AWD,2016,2.5,4.0,Auto(AV-S6),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Regular,9.988182,34,31,33,270.000000,1000,10,1.527525
33375,Toyota,RAV4 Hybrid AWD,2017,2.5,4.0,Auto(AV-S6),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Regular,10.300313,34,30,32,275.000000,1050,10,2.000000

In [136]:
data.query('Cylinders == 4')

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car,std
Make,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,10,0.577350
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,0,0.577350
5,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500,0,3.055050
6,Acura,2.2CL/3.0CL,1997,2.2,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,22,28,24,370.291667,1400,0,3.055050
8,Acura,2.3CL/3.0CL,1998,2.3,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,19,27,22,403.954545,1500,0,4.041452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35927,Yugo,GV Plus/GV/Cabrio,1990,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350,0,2.516611
35928,Yugo,GV/GVX,1987,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300,0,2.516611
35929,Yugo,GV/GVX,1989,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300,0,2.516611
35930,Yugo,GV/GVX,1989,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350,0,2.516611
35931,Yugo,Gy/yugo GVX,1986,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Minicompact Cars,Regular,13.184400,22,29,25,355.480000,1350,0,3.511885

In [133]:
numero_cilindros = 6
data.query(f'Make == "Acura" and Cylinders == {numero_cilindros}')

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,fl_city_car,std
7,Acura,2.2CL/3.0CL,1997,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,18,26,20,444.350000,1650,0,4.163332
10,Acura,2.3CL/3.0CL,1998,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,17,26,20,444.350000,1650,0,4.582576
13,Acura,2.3CL/3.0CL,1999,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,17,26,20,444.350000,1650,0,4.582576
16,Acura,2.5TL/3.2TL,1996,3.2,6.0,Automatic 4-spd,Front-Wheel Drive,Compact Cars,Premium,17.347895,17,22,19,467.736842,2150,0,2.516611
18,Acura,2.5TL/3.2TL,1997,3.2,6.0,Automatic 4-spd,Front-Wheel Drive,Compact Cars,Premium,17.347895,17,22,19,467.736842,2150,0,2.516611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,Acura,TSX,2014,3.5,6.0,Automatic (S5),Front-Wheel Drive,Compact Cars,Premium,14.330870,19,28,23,392.000000,1750,0,4.509250
303,Acura,ZDX 4WD,2010,3.7,6.0,Automatic (S6),All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,17.347895,16,23,19,467.736842,2150,0,3.511885
304,Acura,ZDX 4WD,2011,3.7,6.0,Automatic (S6),All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,17.347895,16,23,19,467.736842,2150,0,3.511885
305,Acura,ZDX 4WD,2012,3.7,6.0,Automatic (S6),All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,17.347895,16,23,19,467.736842,2150,0,3.511885
306,Acura,ZDX 4WD,2013,3.7,6.0,Automatic (S6),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,17.347895,16,23,19,472.000000,2150,0,3.511885

In [ ]:
data.query('`City MPG` > `Highway MPG`')

In [ ]:
numero_cilindros = 4
data.query(f'Make == "Acura" and Cylinders == {numero_cilindros}')